config/routes.rb
Nfl::Application.routes.draw do
  devise_for :users
  resources :schedules

  resources :predictions

  root to: 'predictions#index'

  resources :predictions
  get "user_predictions" , to: "predictions#user", as: :user_predictions  
  resources :predictions
  get "leaders" , to: "predictions#leaders", as: :leaders  
 

end

app/models/prediction.rb
class Prediction < ActiveRecord::Base
	belongs_to :user

  end

app/controllers/predictions_controller.rb
class PredictionsController < ApplicationController
  before_action :set_prediction, only: [:show, :edit, :update, :destroy]
  before_action :calculate_score, only: [:user, :index, :leaders]

  # GET /predictions
  # GET /predictions.json
  def index
    @current = current_week
    @predictions = Prediction.order(score: :desc)
  end

  def leaders
    @predictions = Prediction.all
    @users = User.order(score: :desc)
  end

  def user
    @current = current_week
    @predictions = Prediction.where(user_id: current_user.id)
   end

  # GET /predictions/1
  # GET /predictions/1.json
  def show
  end

  # GET /predictions/new
  def new
    @current = current_week
    @prediction = Prediction.new
  end

  # GET /predictions/1/edit
  def edit
    @current = @prediction.week
  end

  # POST /predictions
  # POST /predictions.json
  def create
    @prediction = Prediction.new(prediction_params)

    respond_to do |format|
      if @prediction.save
        format.html { redirect_to user_predictions_url, notice: 'Prediction was successfully created.' }
        format.json { render action: 'show', status: :created, location: @prediction }
      else
        format.html { render action: 'new' }
        format.json { render json: @prediction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /predictions/1
  # PATCH/PUT /predictions/1.json
  def update
    respond_to do |format|
      if @prediction.update(prediction_params)
        format.html { redirect_to user_predictions_url, notice: 'Prediction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @prediction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /predictions/1
  # DELETE /predictions/1.json
  def destroy
    @prediction.destroy
    respond_to do |format|
      format.html { redirect_to user_predictions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prediction
      @prediction = Prediction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prediction_params
      params.require(:prediction).permit(:week, :week_score, :user_id, :score, :game1, :game2, :game3, :game4, :game5, :game6, :game7, :game8, :game9, :game10, :game11, :game12, :game13, :game14, :game15, :game16)
    end
    
    def current_week
      9
    end

     def calculate_score
      @users = User.all
      @users.each do |user|
        user.score = 0
        @predictions = Prediction.where(user_id: user.id)
        @predictions.each do |prediction|
          prediction.score = 0
          @schedules = Schedule.where(week: prediction.week, game: 1)
          @schedules.each do |schedule|
            if schedule.winner === prediction.game1
              prediction.score += schedule.value
            end
          end
          @schedules = Schedule.where(week: prediction.week, game: 2)
          @schedules.each do |schedule|
            if schedule.winner === prediction.game2
              prediction.score += schedule.value
            end
          end
          @schedules = Schedule.where(week: prediction.week, game: 3)
          @schedules.each do |schedule|
            if schedule.winner === prediction.game3
              prediction.score += schedule.value
            end
          end
          @schedules = Schedule.where(week: prediction.week, game: 4)
          @schedules.each do |schedule|
            if schedule.winner === prediction.game4
              prediction.score += schedule.value
            end
          end
          @schedules = Schedule.where(week: prediction.week, game: 5)
          @schedules.each do |schedule|
            if schedule.winner === prediction.game5
              prediction.score += schedule.value
            end
          end
          @schedules = Schedule.where(week: prediction.week, game: 6)
          @schedules.each do |schedule|
            if schedule.winner === prediction.game6
              prediction.score += schedule.value
            end
          end
          @schedules = Schedule.where(week: prediction.week, game: 7)
          @schedules.each do |schedule|
            if schedule.winner === prediction.game7
              prediction.score += schedule.value
            end
          end
          @schedules = Schedule.where(week: prediction.week, game: 8)
          @schedules.each do |schedule|
            if schedule.winner === prediction.game8
              prediction.score += schedule.value
            end
          end
          @schedules = Schedule.where(week: prediction.week, game: 9)
          @schedules.each do |schedule|
            if schedule.winner === prediction.game9
              prediction.score += schedule.value
            end
          end
          @schedules = Schedule.where(week: prediction.week, game: 10)
          @schedules.each do |schedule|
            if schedule.winner === prediction.game10
              prediction.score += schedule.value
            end
          end
          @schedules = Schedule.where(week: prediction.week, game: 11)
          @schedules.each do |schedule|
            if schedule.winner === prediction.game11
              prediction.score += schedule.value
            end
          end
          @schedules = Schedule.where(week: prediction.week, game: 12)
          @schedules.each do |schedule|
            if schedule.winner === prediction.game12
              prediction.score += schedule.value
            end
          end
          @schedules = Schedule.where(week: prediction.week, game: 13)
          @schedules.each do |schedule|
            if schedule.winner === prediction.game13
              prediction.score += schedule.value
            end
          end
          @schedules = Schedule.where(week: prediction.week, game: 14)
          @schedules.each do |schedule|
            if schedule.winner === prediction.game14
              prediction.score += schedule.value
            end
          end
          @schedules = Schedule.where(week: prediction.week, game: 15)
          @schedules.each do |schedule|
            if schedule.winner === prediction.game15
              prediction.score += schedule.value
            end
          end
          @schedules = Schedule.where(week: prediction.week, game: 16)
          @schedules.each do |schedule|
            if schedule.winner === prediction.game16
              prediction.score += schedule.value
            end
          end
          user.score += prediction.score
          prediction.save
        end
        user.save
      end
    end

end

app/helpers/predictions_helper.rb
module PredictionsHelper
end

app/views/predictions/_form.html.erb
<%= form_for(@prediction) do |f| %>
  <% if @prediction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prediction.errors.count, "error") %> prohibited this prediction from being saved:</h2>

      <ul>
      <% @prediction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <div class="form-inputs">
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.hidden_field :week, :value => @current %>
    <% @schedules  = Schedule.where(week: @current, game: 1) %>
    <% @schedules.each do |schedule| %>
        <% if @prediction.game1? %>
          <%= f.select(:game1, options_for_select([[schedule.team1, 1], [schedule.team0, 0]])) %><br> 
        <% else %>
          <%= f.select(:game1, options_for_select([[schedule.team0, 0], [schedule.team1, 1]])) %><br> 
        <% end %>
    <% end %>
    <% @schedules  = Schedule.where(week: @current, game: 2) %>
    <% @schedules.each do |schedule| %>
        <% if @prediction.game2? %>
          <%= f.select(:game2, options_for_select([[schedule.team1, 1], [schedule.team0, 0]])) %><br> 
        <% else %>
          <%= f.select(:game2, options_for_select([[schedule.team0, 0], [schedule.team1, 1]])) %><br> 
        <% end %>
    <% end %>
    <% @schedules  = Schedule.where(week: @current, game: 3) %>
    <% @schedules.each do |schedule| %>
        <% if @prediction.game3? %>
          <%= f.select(:game3, options_for_select([[schedule.team1, 1], [schedule.team0, 0]])) %><br> 
        <% else %>
          <%= f.select(:game3, options_for_select([[schedule.team0, 0], [schedule.team1, 1]])) %><br> 
        <% end %>
    <% end %>
    <% @schedules  = Schedule.where(week: @current, game: 4) %>
    <% @schedules.each do |schedule| %>
        <% if @prediction.game4? %>
          <%= f.select(:game4, options_for_select([[schedule.team1, 1], [schedule.team0, 0]])) %><br> 
        <% else %>
          <%= f.select(:game4, options_for_select([[schedule.team0, 0], [schedule.team1, 1]])) %><br> 
        <% end %>
    <% end %>
    <% @schedules  = Schedule.where(week: @current, game: 5) %>
    <% @schedules.each do |schedule| %>
        <% if @prediction.game5? %>
          <%= f.select(:game5, options_for_select([[schedule.team1, 1], [schedule.team0, 0]])) %><br> 
        <% else %>
          <%= f.select(:game5, options_for_select([[schedule.team0, 0], [schedule.team1, 1]])) %><br> 
        <% end %>
    <% end %>
    <% @schedules  = Schedule.where(week: @current, game: 6) %>
    <% @schedules.each do |schedule| %>
        <% if @prediction.game6? %>
          <%= f.select(:game6, options_for_select([[schedule.team1, 1], [schedule.team0, 0]])) %><br> 
        <% else %>
          <%= f.select(:game6, options_for_select([[schedule.team0, 0], [schedule.team1, 1]])) %><br> 
        <% end %>
    <% end %>
    <% @schedules  = Schedule.where(week: @current, game: 7) %>
    <% @schedules.each do |schedule| %>
        <% if @prediction.game7? %>
          <%= f.select(:game7, options_for_select([[schedule.team1, 1], [schedule.team0, 0]])) %><br> 
        <% else %>
          <%= f.select(:game7, options_for_select([[schedule.team0, 0], [schedule.team1, 1]])) %><br> 
        <% end %>
    <% end %>
    <% @schedules  = Schedule.where(week: @current, game: 8) %>
    <% @schedules.each do |schedule| %>
        <% if @prediction.game8? %>
          <%= f.select(:game8, options_for_select([[schedule.team1, 1], [schedule.team0, 0]])) %><br> 
        <% else %>
          <%= f.select(:game8, options_for_select([[schedule.team0, 0], [schedule.team1, 1]])) %><br> 
        <% end %>
    <% end %>
    <% @schedules  = Schedule.where(week: @current, game: 9) %>
    <% @schedules.each do |schedule| %>
        <% if @prediction.game9? %>
          <%= f.select(:game9, options_for_select([[schedule.team1, 1], [schedule.team0, 0]])) %><br> 
        <% else %>
          <%= f.select(:game9, options_for_select([[schedule.team0, 0], [schedule.team1, 1]])) %><br> 
        <% end %>
    <% end %>
    <% @schedules  = Schedule.where(week: @current, game: 10) %>
    <% @schedules.each do |schedule| %>
        <% if @prediction.game10? %>
          <%= f.select(:game10, options_for_select([[schedule.team1, 1], [schedule.team0, 0]])) %><br> 
        <% else %>
          <%= f.select(:game10, options_for_select([[schedule.team0, 0], [schedule.team1, 1]])) %><br> 
        <% end %>
    <% end %>
    <% @schedules  = Schedule.where(week: @current, game: 11) %>
    <% @schedules.each do |schedule| %>
        <% if @prediction.game11? %>
          <%= f.select(:game11, options_for_select([[schedule.team1, 1], [schedule.team0, 0]])) %><br> 
        <% else %>
          <%= f.select(:game11, options_for_select([[schedule.team0, 0], [schedule.team1, 1]])) %><br> 
        <% end %>
    <% end %>
    <% @schedules  = Schedule.where(week: @current, game: 12) %>
    <% @schedules.each do |schedule| %>
        <% if @prediction.game12? %>
          <%= f.select(:game12, options_for_select([[schedule.team1, 1], [schedule.team0, 0]])) %><br> 
        <% else %>
          <%= f.select(:game12, options_for_select([[schedule.team0, 0], [schedule.team1, 1]])) %><br> 
        <% end %>
    <% end %>
    <% @schedules  = Schedule.where(week: @current, game: 13) %>
    <% @schedules.each do |schedule| %>
        <% if @prediction.game13? %>
          <%= f.select(:game13, options_for_select([[schedule.team1, 1], [schedule.team0, 0]])) %><br> 
        <% else %>
          <%= f.select(:game13, options_for_select([[schedule.team0, 0], [schedule.team1, 1]])) %><br> 
        <% end %>
    <% end %>
    <% @schedules  = Schedule.where(week: @current, game: 14) %>
    <% @schedules.each do |schedule| %>
        <% if @prediction.game14? %>
          <%= f.select(:game14, options_for_select([[schedule.team1, 1], [schedule.team0, 0]])) %><br> 
        <% else %>
          <%= f.select(:game14, options_for_select([[schedule.team0, 0], [schedule.team1, 1]])) %><br> 
        <% end %>
    <% end %>
    <% @schedules  = Schedule.where(week: @current, game: 15) %>
    <% @schedules.each do |schedule| %>
        <% if @prediction.game15? %>
          <%= f.select(:game15, options_for_select([[schedule.team1, 1], [schedule.team0, 0]])) %><br> 
        <% else %>
          <%= f.select(:game15, options_for_select([[schedule.team0, 0], [schedule.team1, 1]])) %><br> 
        <% end %>
    <% end %>
    <% @schedules  = Schedule.where(week: @current, game: 16) %>
    <% @schedules.each do |schedule| %>
        <% if @prediction.game16? %>
          <%= f.select(:game16, options_for_select([[schedule.team1, 1], [schedule.team0, 0]])) %><br> 
        <% else %>
          <%= f.select(:game16, options_for_select([[schedule.team0, 0], [schedule.team1, 1]])) %><br> 
        <% end %>
    <% end %>
 </div>
    <%= f.button :submit %>

<% end %>

app/views/predictions/edit.html.erb
<h1>Editing prediction</h1>

<%= render 'form' %>

<%= link_to 'Back', user_predictions_path %>

app/views/predictions/leaders.html.erb
<h1>Leader Board</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Score</th>

    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
     <% if user.score != 0 %>
       <tr>
         <td><p><%= user.user_name %></p></td>
         <td><p><%= user.score %></p></td>
       </tr>
     <% end %>
    <% end %>
  </tbody>
</table>

app/views/predictions/new.html.erb
<h1>New prediction for week  <%= @current %></h1>
<% @prediction.user_id = current_user.id %>

<%= render 'form' %>

<%= link_to 'Back', user_predictions_path %>

app/views/predictions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Week:</strong>
  <%= @prediction.week %>
</p>
<p>
  <strong>User Id:</strong>
  <%= @prediction.user_id %>
</p>

<p>
  <strong>Score:</strong>
  <%= @prediction.score %>
</p>

<p>
  <strong>Game1:</strong>
  <%= @prediction.game1 %>
</p>

<p>
  <strong>Game2:</strong>
  <%= @prediction.game2 %>
</p>

<p>
  <strong>Game3:</strong>
  <%= @prediction.game3 %>
</p>

<p>
  <strong>Game4:</strong>
  <%= @prediction.game4 %>
</p>

<p>
  <strong>Game5:</strong>
  <%= @prediction.game5 %>
</p>

<p>
  <strong>Game6:</strong>
  <%= @prediction.game6 %>
</p>

<p>
  <strong>Game7:</strong>
  <%= @prediction.game7 %>
</p>

<p>
  <strong>Game8:</strong>
  <%= @prediction.game8 %>
</p>

<p>
  <strong>Game9:</strong>
  <%= @prediction.game9 %>
</p>

<p>
  <strong>Game10:</strong>
  <%= @prediction.game10 %>
</p>

<p>
  <strong>Game11:</strong>
  <%= @prediction.game11 %>
</p>

<p>
  <strong>Game12:</strong>
  <%= @prediction.game12 %>
</p>

<p>
  <strong>Game13:</strong>
  <%= @prediction.game13 %>
</p>

<p>
  <strong>Game14:</strong>
  <%= @prediction.game14 %>
</p>

<p>
  <strong>Game15:</strong>
  <%= @prediction.game15 %>
</p>

<p>
  <strong>Game16:</strong>
  <%= @prediction.game16 %>
</p>

<%= link_to 'Edit', edit_prediction_path(@prediction) %> |
<%= link_to 'Back', predictions_path %>

app/views/predictions/user.html.erb
<h1>My Predictions</h1>
           <table>
            <thead>
              <tr>
                <th>Week</th>
                <th>Score</th>
 
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
              </tr>
            </thead>

            <tbody>
              <% @predictions.each do |prediction| %>
                <tr>
                  <td><p><%= prediction.week %></p></td>
                  <td><p><%= prediction.score %></p></td>
                  <% @schedules  = Schedule.where(week: prediction.week, game: 1) %>
                  <% @schedules.each do |schedule| %>

                    <td>
                      <% if prediction.game1? %>
                          <p <% if schedule.winner === 1 %> class="text-success" <% end %> > <%= schedule.team1 %> </p>
                      <% else %>
                          <p <% if schedule.winner === 0 %> class="text-success" <% end %> > <%= schedule.team0 %> </p>
                     <% end %>
                    </td>
                  <% end %> 
                  <% @schedules  = Schedule.where(week: prediction.week, game: 2) %>
                  <% @schedules.each do |schedule| %>
                    <td>
                      <% if prediction.game2? %>
                         <p <% if schedule.winner === 1 %> class="text-success" <% end %> > <%= schedule.team1 %> </p>
                      <% else %>
                         <p <% if schedule.winner === 0 %> class="text-success" <% end %> > <%= schedule.team0 %> </p>
                       <% end %>
                    </td>
                  <% end %> 
                  <% @schedules  = Schedule.where(week: prediction.week, game: 3) %>
                  <% @schedules.each do |schedule| %>
                    <td>
                      <% if prediction.game3? %>
                         <p <% if schedule.winner === 1 %> class="text-success" <% end %> > <%= schedule.team1 %> </p>
                      <% else %>
                         <p <% if schedule.winner === 0 %> class="text-success" <% end %> > <%= schedule.team0 %> </p>
                      <% end %>
                      <% if prediction.game3 == schedule.winner %>
                        <% prediction.score += 1 %>
                        <% end %>
                    </td>
                  <% end %> 
                  <% @schedules  = Schedule.where(week: prediction.week, game: 4) %>
                  <% @schedules.each do |schedule| %>
                    <td>
                      <% if prediction.game4? %>
                         <p <% if schedule.winner === 1 %> class="text-success" <% end %> > <%= schedule.team1 %> </p>
                      <% else %>
                         <p <% if schedule.winner === 0 %> class="text-success" <% end %> > <%= schedule.team0 %> </p>
                      <% end %>
                      <% if prediction.game4 == schedule.winner %>
                        <% prediction.score += 1 %>
                        <% end %>
                    </td>
                  <% end %> 
                  <% @schedules  = Schedule.where(week: prediction.week, game: 5) %>
                  <% @schedules.each do |schedule| %>
                    <td>
                      <% if prediction.game5? %>
                         <p <% if schedule.winner === 1 %> class="text-success" <% end %> > <%= schedule.team1 %> </p>
                      <% else %>
                         <p <% if schedule.winner === 0 %> class="text-success" <% end %> > <%= schedule.team0 %> </p>
                      <% end %>
                      <% if prediction.game5 == schedule.winner %>
                        <% prediction.score += 1 %>
                        <% end %>
                    </td>
                  <% end %> 
                  <% @schedules  = Schedule.where(week: prediction.week, game: 6) %>
                  <% @schedules.each do |schedule| %>
                    <td>
                      <% if prediction.game6? %>
                         <p <% if schedule.winner === 1 %> class="text-success" <% end %> > <%= schedule.team1 %> </p>
                      <% else %>
                         <p <% if schedule.winner === 0 %> class="text-success" <% end %> > <%= schedule.team0 %> </p>
                      <% end %>
                      <% if prediction.game6 == schedule.winner %>
                        <% prediction.score += 1 %>
                        <% end %>
                    </td>
                  <% end %> 
                  <% @schedules  = Schedule.where(week: prediction.week, game: 7) %>
                  <% @schedules.each do |schedule| %>
                    <td>
                      <% if prediction.game7? %>
                         <p <% if schedule.winner === 1 %> class="text-success" <% end %> > <%= schedule.team1 %> </p>
                      <% else %>
                         <p <% if schedule.winner === 0 %> class="text-success" <% end %> > <%= schedule.team0 %> </p>
                      <% end %>
                      <% if prediction.game7 == schedule.winner %>
                        <% prediction.score += 1 %>
                        <% end %>
                    </td>
                  <% end %> 
                  <% @schedules  = Schedule.where(week: prediction.week, game: 8) %>
                  <% @schedules.each do |schedule| %>
                    <td>
                      <% if prediction.game8? %>
                         <p <% if schedule.winner === 1 %> class="text-success" <% end %> > <%= schedule.team1 %> </p>
                      <% else %>
                         <p <% if schedule.winner === 0 %> class="text-success" <% end %> > <%= schedule.team0 %> </p>
                      <% end %>
                      <% if prediction.game8 == schedule.winner %>
                        <% prediction.score += 1 %>
                        <% end %>
                    </td>
                  <% end %> 
                  <% @schedules  = Schedule.where(week: prediction.week, game: 9) %>
                  <% @schedules.each do |schedule| %>
                    <td>
                      <% if prediction.game9? %>
                         <p <% if schedule.winner === 1 %> class="text-success" <% end %> > <%= schedule.team1 %> </p>
                      <% else %>
                         <p <% if schedule.winner === 0 %> class="text-success" <% end %> > <%= schedule.team0 %> </p>
                      <% end %>
                      <% if prediction.game9 == schedule.winner %>
                        <% prediction.score += 1 %>
                        <% end %>
                    </td>
                  <% end %> 
                  <% @schedules  = Schedule.where(week: prediction.week, game: 10) %>
                  <% @schedules.each do |schedule| %>
                    <td>
                      <% if prediction.game10? %>
                         <p <% if schedule.winner === 1 %> class="text-success" <% end %> > <%= schedule.team1 %> </p>
                      <% else %>
                         <p <% if schedule.winner === 0 %> class="text-success" <% end %> > <%= schedule.team0 %> </p>
                      <% end %>
                      <% if prediction.game10 == schedule.winner %>
                        <% prediction.score += 1 %>
                        <% end %>
                    </td>
                  <% end %> 
                  <% @schedules  = Schedule.where(week: prediction.week, game: 11) %>
                  <% @schedules.each do |schedule| %>
                    <td>
                      <% if prediction.game11? %>
                         <p <% if schedule.winner === 1 %> class="text-success" <% end %> > <%= schedule.team1 %> </p>
                      <% else %>
                         <p <% if schedule.winner === 0 %> class="text-success" <% end %> > <%= schedule.team0 %> </p>
                      <% end %>
                      <% if prediction.game11 == schedule.winner %>
                        <% prediction.score += 1 %>
                        <% end %>
                    </td>
                  <% end %> 
                  <% @schedules  = Schedule.where(week: prediction.week, game: 12) %>
                  <% @schedules.each do |schedule| %>
                    <td>
                      <% if prediction.game12? %>
                         <p <% if schedule.winner === 1 %> class="text-success" <% end %> > <%= schedule.team1 %> </p>
                      <% else %>
                         <p <% if schedule.winner === 0 %> class="text-success" <% end %> > <%= schedule.team0 %> </p>
                      <% end %>
                      <% if prediction.game12 == schedule.winner %>
                        <% prediction.score += 1 %>
                        <% end %>
                    </td>
                  <% end %> 
                  <% @schedules  = Schedule.where(week: prediction.week, game: 13) %>
                  <% @schedules.each do |schedule| %>
                    <td>
                      <% if prediction.game13? %>
                         <p <% if schedule.winner === 1 %> class="text-success" <% end %> > <%= schedule.team1 %> </p>
                      <% else %>
                         <p <% if schedule.winner === 0 %> class="text-success" <% end %> > <%= schedule.team0 %> </p>
                      <% end %>
                      <% if prediction.game13 == schedule.winner %>
                        <% prediction.score += 1 %>
                        <% end %>
                    </td>
                  <% end %> 
                  <% @schedules  = Schedule.where(week: prediction.week, game: 14) %>
                  <% @schedules.each do |schedule| %>
                    <td>
                      <% if prediction.game14? %>
                         <p <% if schedule.winner === 1 %> class="text-success" <% end %> > <%= schedule.team1 %> </p>
                      <% else %>
                         <p <% if schedule.winner === 0 %> class="text-success" <% end %> > <%= schedule.team0 %> </p>
                      <% end %>
                      <% if prediction.game14 == schedule.winner %>
                        <% prediction.score += 1 %>
                        <% end %>
                    </td>
                  <% end %> 
                  <% @schedules  = Schedule.where(week: prediction.week, game: 15) %>
                  <% @schedules.each do |schedule| %>
                    <td>
                      <% if prediction.game15? %>
                         <p <% if schedule.winner === 1 %> class="text-success" <% end %> > <%= schedule.team1 %> </p>
                      <% else %>
                         <p <% if schedule.winner === 0 %> class="text-success" <% end %> > <%= schedule.team0 %> </p>
                      <% end %>
                      <% if prediction.game15 == schedule.winner %>
                        <% prediction.score += 1 %>
                        <% end %>
                    </td>
                  <% end %> 
                  <% @schedules  = Schedule.where(week: prediction.week, game: 16) %>
                  <% @schedules.each do |schedule| %>
                    <td>
                      <% if prediction.game16? %>
                         <p <% if schedule.winner === 1 %> class="text-success" <% end %> > <%= schedule.team1 %> </p>
                      <% else %>
                         <p <% if schedule.winner === 0 %> class="text-success" <% end %> > <%= schedule.team0 %> </p>
                      <% end %>
                      <% if prediction.game16 == schedule.winner %>
                        <% prediction.score += 1 %>
                        <% end %>
                    </td>
                  <% end %> 
                  <% if prediction.week == @current %>
                    <% @current_exists = true %>
                    <td><p><%= link_to 'Edit', edit_prediction_path(prediction) %></p></td>
                    <td><p><%= link_to 'Delete', prediction, method: :delete, data: { confirm: 'Are you sure?' } %></p></td>
                  <% end %>
                </tr>
              <% end %>
            </tbody>
          </table>
         <table>
            <thead>
              <tr>
                <th>Total</th>
                <% prediction = @predictions.first %>
                <% if prediction != nil %>
                  <th><%= prediction.user.score %></th>
                <% end %>
              </tr>
            </thead>
          </table>

<% if @current_exists != true %>
  <%= link_to "Add This Week's Prediction", new_prediction_path %>
<% end %>
</div>

<br>