config/routes.rb
Nfl::Application.routes.draw do
  devise_for :users
  resources :schedules

  resources :predictions

  root to: 'predictions#index'

  resources :predictions
  get "user_predictions" , to: "predictions#user", as: :user_predictions  
  resources :predictions
  get "leaders" , to: "predictions#leaders", as: :leaders  
 

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to schedules_url}
        format.json { head :no_content }
      else
        format.html { render action: 'new' }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to schedule_url, notice: 'Schedule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:week, :game, :team0, :team1, :winner, :value)
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 
  <div class="field">
    <%= f.label :week %><br>
    <%= f.number_field :week %>
  </div>
  <div class="field">
    <%= f.label :game %><br>
    <%= f.number_field :game %>
  </div>
  <div class="field">
    <%= f.label :team0 %><br>
    <%= f.text_field :team0 %>
  </div>
  <div class="field">
    <%= f.label :team1 %><br>
    <%= f.text_field :team1 %>
  </div>
  <div class="field">
    <%= f.label :winner %><br>
    <%= f.number_field :winner %>
  </div>
    <%= f.hidden_field :value, :value => 1 %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<h1>Listing schedules</h1>

<table>
  <thead>
    <tr>
      <th>Week</th>
      <th>Game</th>
      <th>Team0</th>
      <th>Team1</th>
      <th>Winner</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.week %></td>
        <td><%= schedule.game %></td>
        <td><%= schedule.team0 %></td>
        <td><%= schedule.team1 %></td>
        <td><%= schedule.winner %></td>
        <td><%= link_to 'Show', schedule %></td>
        <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
        <td><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<h1>New schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Week:</strong>
  <%= @schedule.week %>
</p>

<p>
  <strong>Game:</strong>
  <%= @schedule.game %>
</p>

<p>
  <strong>Team0:</strong>
  <%= @schedule.team0 %>
</p>

<p>
  <strong>Team1:</strong>
  <%= @schedule.team1 %>
</p>

<p>
  <strong>Winner:</strong>
  <%= @schedule.winner %>
</p>
<p>
  <strong>Value:</strong>
  <%= @schedule.value %>
</p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>